---

- name: Package | Install lists packages
  dnf:
    name:
      - mpv
      - webp-pixbuf-loader
      - libwebp
      - gthumb
      #- lmms
      - ffmpeg
      - x264
      - x265
      #- audacity
      - transmission
      #- clementine
      #- pitivi
      #- gstreamer1-plugin-openh264
      #- gstreamer1-plugins-bad-free-extras
      #- gstreamer1-plugins-bad-freeworld
      #- gstreamer1-plugins-good-extras
      #- gstreamer1-plugins-ugly
      #- gstreamer1-vaapi
      #- PackageKit-gstreamer-plugin
      #- steam
      #- dolphin-emu
      #- strawberry
    state: latest

- name: Install Flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
      - org.audacityteam.Audacity
      - io.lmms.LMMS
      - clementine
      - strawberry
      - org.pitivi.Pitivi
      - kdenlive
      - org.blender.Blender
      - org.gnome.NautilusPreviewer
      - tv.plex.PlexDesktop 
      - com.github.iwalton3.jellyfin-media-player

      
         
