---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache ( RHEL )
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Rocky", "Almalinux"]

- hosts: localhost
  become: true
  roles:
    - common
    - workstation
    - plasma
    - design
    - communication
    - browsers
    - dev
    - multimedia
    - virtualization
    - users
