---
#- name: Install Gnome
#  dnf:
#    name: '@GNOME Desktop Environment'
#    state: present

- name: Install Workstation
  dnf:
    name: '@Workstation'
    state: present

- name: Set default boot target to graphical mode
  shell: systemctl set-default graphical.target
    
- name: Package | Install lists packages
  dnf:
    name:
  
      - bash-completion
      - vim
      - git
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      - tmux
      - terminator
      - tig
      - unzip
      - squashfs-tools
      - unrar
      - p7zip
      - mc
      - sshfs
      - gnome-tweak-tool
      - util-linux-user
      - qt5ct
      #- yaru-theme
      - gnome-extensions-app
      #- gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-system-monitor
      - gnome-shell-extension-top-icons
      - gnome-shell-extension-vertical-workspaces
      - gnome-shell-extension-auto-move-windows
      #- gnome-shell-extension-pop-shell
      #- gnome-shell-extension-systemMonitor
      #- gnome-shell-extension-sound-output-device-chooser

      #- gnome-shell-theme-yaru
      - libwebp
      #- pdf2djvu
      - poppler-utils
      - ImageMagick
      - xclip
      #- libreoffice-langpack-pt-BR
      - yakuake
      - zsh
      - ffmpegthumbnailer
      - ffmpegthumbs

    state: installed

- name: Enable GDM
  service:
    name: gdm
    enabled: yes
    state: started

- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

- name: Add flathub repo
  shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Nextcloud
  community.general.flatpak:
    name: com.nextcloud.desktopclient.nextcloud

- name: Install Misc tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - net.cozic.joplin_desktop
    - io.appflowy.AppFlowy
    - com.github.tchx84.Flatseal
    - rocks.koreader.KOReader
