---

- name: Add flathub repo
  shell: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Nextcloud
  community.general.flatpak:
    name: com.nextcloud.desktopclient.nextcloud

- name: Install Creation tools
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.gimp.GIMP
    - org.inkscape.Inkscape
    - org.blender.Blender
    - org.kde.kdenlive
    - com.obsproject.Studio
