---
- name: uninstall Teams
  flatpak:
    name: com.microsoft.Teams
    state: absent

- name: uninstall Anydesk
  flatpak:
    name: com.anydesk.Anydesk
    state: absent

- name: Install Geary
  flatpak:
    name: org.gnome.Geary
    state: present  


- name: Install Slack
  flatpak:
    name: com.slack.Slack
    state: present

- name: Install Discord Snap
  flatpak:
    name: com.discordapp.Discord
    state: present

