---
- name: Install YUM Utils
  shell: yum install -y yum-utils

- name: Install vagrant repo
  shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo 

- name: Virtualization | Install lists packages
  dnf:
    name:
      #- VirtualBox
      - vagrant
      #- libvirt-daemon-vbox
      #- docker-vim
      #- docker-selinux
      #- docker
      - podman-compose
      - podman
      - binutils
      - gcc
      - make
      - cmake
      - go
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms
    state: latest

      #- name: Enable docker
      #  service:
      #    name: docker
      #    state: started
      #    enabled: yes

