---

- name: Setup SSHD
  service: name=sshd state=started enabled=yes

- name: Enable CRB
  shell: dnf config-manager --set-enabled crb
  when: ansible_distribution == "Rockylinux"

- name: Enable CRB RHEL
  shell: subscription-manager repos --enable codeready-builder-for-rhel-10-x86_64-rpms
  when: ansible_distribution == "Red Hat Enterprise Linux"  

- name: Install REMI
  dnf: name=http://mirror.digitalnova.at/remi/enterprise/remi-release-10.rpm state=latest disable_gpg_check=yes

- name: Install ELREPO
  dnf: name=https://www.elrepo.org/elrepo-release-10.el10.elrepo.noarch.rpm state=latest disable_gpg_check=yes

- name: Install EPEL
  dnf: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion free
  dnf: name=https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-10.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion nonfree
  dnf: name=https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-10.noarch.rpm state=latest disable_gpg_check=yes

- name: Package | Install lists packages
  dnf:
    update_cache: yes
    name:
  
      - zsh
      - bash-completion
      - openssh-server
      - vim
      - git
      - tig
      - NetworkManager-tui
      #- unar
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      #- ccze
      - tmux
      - tig
      - unzip
      - fastfetch
      - iotop
      - pciutils
      - usbutils
      - nmap
      #- youtube-dl
      - squashfs-tools
      #- shntool
      - unrar
      - p7zip
      - mc
      #- nnn
      - sshfs
      - util-linux-user
      - libwebp
      - poppler-utils
      - ImageMagick
      - xclip
      #- compsize
      #- fortune-mod
      - cockpit
      - cockpit-bridge
      - cockpit-composer
      - cockpit-files
      - cockpit-machines
      - cockpit-podman
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws

    state: installed
