---
- name: Setup SSHD
  service: name=sshd state=started enabled=yes

#- name: Setup dependencies
#  dnf:
#    name:
#      - python3-dnf

- name: Install EPEL
  dnf: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion free
  dnf: name=https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm state=latest disable_gpg_check=yes

- name: Install RPMfusion nonfree
  dnf: name=https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm state=latest disable_gpg_check=yes

#- name: Team Viewer
#  dnf: name=https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm disable_gpg_check=yes

- name: Install Gnome
  dnf:
    name: '@GNOME Desktop Environment'
    state: present

- name: Install Workstation
  dnf:
    name: '@Workstation'
    state: present



- name: Package | Install lists packages
  dnf:
    name:
      - zsh
      #- geary
      - bash-completion
      - openssh-server
      - vim
      - git
      - NetworkManager-tui
      - unar
      - htop
      - tree
      - dstat
      - screen
      - curl
      - wget
      - ccze
      - tmux
      - terminator
      - tig
      - unzip
      - neofetch
      - iotop
      - pciutils
      - usbutils
      - nmap
      - youtube-dl
      - squashfs-tools
      #- shntool
      - unrar
      - p7zip
      - mc
      - nnn
      - syncthing
      - sshfs
      - gnome-tweak-tool
      - util-linux-user
      - qt5ct
      #- yaru-theme
      #- gnome-shell-extension-netspeed
      #- gnome-shell-theme-selene
      #- chrome-gnome-shell
      #- gnome-shell-extension-appindicator
      #- gnome-shell-extension-desktop-icons
      #- gnome-shell-extension-dash-to-dock
      #- gnome-shell-extension-freon
      #- gnome-shell-extension-gamemode
      #- gnome-shell-extension-gsconnect
      #- gnome-shell-extension-media-player-indicator
      #- gnome-shell-extension-pomodoro
      #- gnome-shell-extension-system-monitor-applet
      #- gnome-shell-extension-topicons-plus
      #- gnome-shell-theme-yaru
      - libwebp
      #- pdf2djvu
      - poppler-utils
      - ImageMagick
      - xclip
      - libreoffice-langpack-pt-BR
      #- compsize
      #- foliate
      - yakuake
      - fortune-mod
      - zsh
      #- ffmpegthumbnailer
      #- ffmpegthumbs
      
    state: installed

- name: Enable GDM
  service:
    name: gdm
    enabled: yes
    state: started

- name: Install webp thumbnailer
  template:
    src: webp.thumbnailer
    dest: /usr/share/thumbnailers/
    owner: root
    group: root
    mode: '0644'

