---
- name: Install Dev tools
  dnf:
    name: '@Development tools'
    state: present
    
- name: Remove some packages 
  dnf:
    name:
      - libX11-devel
      - libXcursor-devel 
      - libXrandr-devel
      - libXinerama-devel
      - libXi-devel
      - mesa-libGL-devel
      - SDL2_gfx-devel
      - SDL2_image-devel
      - SDL2_mixer-devel
      - SDL2_ttf-devel
      - SDL2-devel
      - SDL3-devel
      - libXxf86vm-devel
      - glib-devel
      - glib2-devel

    disable_gpg_check: no
    state: installed
    
- name: Install X11 libs
  dnf:
    name:

      - gcc-c++
      - intltool
      - libtool
      - fira-code-fonts
      - cargo
      - nix
      - uv
      - conda
      - python-unversioned-command
      
    disable_gpg_check: no
    state: installed


#- name: Install "phpstorm" 
#  flatpak:
#    name: com.jetbrains.PhpStorm
#    state: present

#- name: Install "goland" 
#  flatpak:
#    name: com.jetbrains.Goland
#    state: present

#- name: Install "Pycharm-Professional"                      
#  flatpak:
#    name: com.jetbrains.Pycharm-Professional
#    state: present

#- name: Install "WebStorm"                      
#  flatpak:
#    name: com.jetbrains.WebStorm
#    state: present

- name: Install "DBeaver"
  flatpak:
    name: io.dbeaver.DBeaverCommunity 
    state: present

- name: Add MS keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VSCode repository
  yum_repository:
    name: vscode
    description: vscode repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes

- name: VSCode
  dnf: pkg=code state=latest

- name: Install "micro"
  dnf:
    name: micro

#- name: Install "zeal"
#  flatpak:
#    name: org.zealdocs.Zeal
#    state: present

- name: Install Eng Stuff
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - org.fritzing.Fritzing
    - org.openscad.OpenSCAD
    - com.prusa3d.PrusaSlicer
    - com.ultimaker.cura

